 module.exports = {
    ADMIN_BLOCKED_MANAGER : "ADMIN_BLOCKED_MANAGER",
    ADMIN_UNBLOCKED_MANAGER : "ADMIN_UNBLOCKED_MANAGER",
    ADMIN_APPROVED_MANAGER_PROFILE : "ADMIN_APPROVED_MANAGER_PROFILE",
    ADMIN_REMOVED_PLAYER_FROM_TEAM : "ADMIN_REMOVED_PLAYER_FROM_TEAM",
    ADMIN_CHANGED_PLAYER_TEAM : "ADMIN_CHANGED_PLAYER_TEAM",
   
    MANAGER_APPROVED_PLAYER_PROFILE : "MANAGER_APPROVED_PLAYER_PROFILE",
    MANAGER_APPROVED_CHANGE_PLAYER_TEAM : "MANAGER_APPROVED_CHANGE_PLAYER_TEAM",
    MANAGER_APPROVED_LEFT_PLAYER_TEAM : "MANAGER_APPROVED_LEFT_PLAYER_TEAM",
    MANAGER_DISAPPROVED_PLAYER_PROFILE : "MANAGER_DISAPPROVED_PLAYER_PROFILE",
    MANAGER_DISAPPROVED_CHANGE_PLAYER_TEAM : "MANAGER_DISAPPROVED_CHANGE_PLAYER_TEAM",
    MANAGER_DISAPPROVED_LEFT_PLAYER_FROM_TEAM : "MANAGER_DISAPPROVED_LEFT_PLAYER_FROM_TEAM",
   
    PLAYER_WANT_CHANGING_TEAM : "PLAYER_WANT_CHANGING_TEAM",
    PLAYER_WANT_LEFT_TEAM : "PLAYER_WANT_LEFT_TEAM",
    PLAYER_DISAPPROVED_CHANGING_TEAM : "PLAYER_DISAPPROVED_CHANGING_TEAM",
    PLAYER_DISAPPROVED_LIVE_FROM_TEAM : "PLAYER_DISAPPROVED_LIVE_FROM_TEAM",
    NEW_USER_WAS_REGISTRATED : "NEW_USER_WAS_REGISTRATED",
 };


