export const CHANGING_TEAM = "CHANGING_TEAM";
export const NEW_USER_REGISTRATED = "NEW_USER_REGISTRATED";
export const BLOCKING_USER_ACCOUTN = "BLOCKING_USER_ACCOUTN";
export const GIVING_USER_ACCESS = "GIVING_USER_ACCESS";
