export const LOADING_USERS = "LOADING_USERS";
export const USERS_LOADED = "USERS_LOADED";
export const LOADING_USER_INFO = "LOADING_USER_INFO";
export const USER_INFO_LOADED = "USER_INFO_LOADED";

export const USER_CHANGE_TEAM = "USER_CHANGE_TEAM";
export const USER_CHANGE_STATUS = "USER_CHANGED_STATUS";
export const USER_TEAM_UPDATING = "USER_TEAM_UPDATING";
export const USER_TEAM_UPDATED = "USER_TEAM_UPDATED";
export const USER_BLOCKED = "USER_BLOCKED";
export const UNBLOCKED_USER = "UNBLOCKED_USER";
export const PLAYER_LIVE_TEAM = "PLAYER_LIVE_TEAM";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTRATION = "USER_REGISTRATION";

export const LOADING_TEAMS = "LOADING_TEAMS";
export const TEAMS_LOADED = "TEAMS_LOADED";
export const LOADING_TEAM_INFO = "LOADING_TEAM_INFO";
export const TEAM_INFO_LOADED = "TEAM_INFO_LOADED";

export const LOADING_NOTIFICATIONS = "LOADING_NOTIFICATIONS";
export const NOTIFICATIONS_LOADED = "NOTIFICATIONS_LOADED";

export const UPDATE_STATUS = "UPDATE_STATUS";
export const RESET_ERROR_STATUS = "RESET_ERROR_STATUS";
export const GET_TOKEN = "GET_TOKEN";

export const LOADING_MY_PROFILE = "LOADING_MY_PROFILE";
export const SET_PROFILE = "SET_PROFILE";