export const ADMIN_BLOCKED_MANAGER = "ADMIN_BLOCKED_MANAGER";
export const ADMIN_BLOCKED_PLAYER = "ADMIN_BLOCKED_PLAYER";
export const ADMIN_APPROVED_MANAGER_PROFILE = "ADMIN_APPROVED_MANAGER_PROFILE";
export const ADMIN_APPROVED_PLAYER_PROFILE = "ADMIN_APPROVED_PLAYER_PROFILE";
export const ADMIN_REMOVED_PLAYER_FROM_TEAM = "ADMIN_REMOVED_PLAYER_FROM_TEAM";
export const ADMIN_APPROVED_LEFT_PLAYER_FROM_TEAM = "ADMIN_APPROVED_LEFT_PLAYER_FROM_TEAM";
export const ADMIN_DISAPROVED_LEFT_PLAYER_FROM_TEAM = "ADMIN_DISAPROVED_LEFT_PLAYER_FROM_TEAM";
export const ADMIN_CHANGED_PLAYER_TEAM = "ADMIN_CHANGED_PLAYER_TEAM";

export const MANAGER_APPROVED_PLAYER_PROFILE  = "MANAGER_APPROVED_PLAYER_PROFILE";
export const MANAGER_APPROVED_CHANGE_PLAYER_TEAM  = "MANAGER_APPROVED_CHANGE_PLAYER_TEAM";
export const MANAGER_APPROVED_LEFT_PLAYER_TEAM  = "MANAGER_APPROVED_LEFT_PLAYER_TEAM";
export const MANAGER_BLOKED_PLAYER_PROFILE  = "MANAGER_BLOKED_PLAYER_PROFILE";
export const MANAGER_DISAPPROVED_CHANGE_PLAYER_TEAM  = "MANAGER_DISAPPROVED_CHANGE_PLAYER_TEAM";
export const MANAGER_DISAPPROVED_LEFT_PLAYER_FROM_TEAM  = "MANAGER_DISAPPROVED_LEFT_PLAYER_FROM_TEAM";
export const MANAGER_REMOVE_PLAYAER_FROM_TEAM = "MANAGER_REMOVE_PLAYAER_FROM_TEAM";
export const MANAGER_CHANGED_PLAYER_TEAM = "MANAGER_CHANGED_PLAYER_TEAM";

export const PLAYER_CHANGING_TEAM  = "PLAYER_CHANGING_TEAM";
export const PLAYER_LEFT_TEAM  = "PLAYER_LEFT_TEAM";
export const PLAYER_DISAPPROVED_CHANGE_TEAM  = "PLAYER_DISAPPROVED_CHANGE_TEAM";
export const PLAYER_DISAPPROVED_LIVE_FROM_TEAM  = "PLAYER_DISAPPROVED_LIVE_FROM_TEAM";
export const NEW_USER_WAS_REGISTRATED  = "NEW_USER_WAS_REGISTRATED";